title: Pomodoro
description: "A series of video classed about using Arduino to produce advanced asynchronous feedback produced fot the students of Interaction & Electronics"

theme: jekyll-theme-minimal
logo: ./illustration/poster.jpeg
show_downloads: "true"
google_analytics: UA-134939299-1
