title: Pomodoro
description: A series of video classed about using Arduino to produce advanced asynchronous feedback.

theme: jekyll-theme-minimal
logo: ./illustration/poster.jpeg
show_downloads: "true"
google_analytics: UA-134939299-1
